const BOOKING_UUID_PATTERN =
  /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;

/**
 * Booking QR codes generated by the API contain the booking UUID. Keep the
 * reader tolerant of a future deep-link/URL wrapper, while never forwarding
 * arbitrary QR contents to the booking lookup endpoint.
 */
export function getBookingIdFromQrPayload(payload: string): string | null {
  const value = payload.trim();
  if (!value) return null;

  const candidates = [value];
  try {
    const decoded = decodeURIComponent(value);
    if (decoded !== value) candidates.push(decoded);
  } catch {
    // A malformed URI is still safe to inspect as its original raw text.
  }

  for (const candidate of candidates) {
    const match = candidate.match(BOOKING_UUID_PATTERN);
    if (match) return match[0].toLowerCase();
  }

  return null;
}
