export type NotificationType =
  | 'SYSTEM'
  | 'VEHICLE_MAINTENANCE_CREATED'
  | 'MAINTENANCE_LOG_UPDATED'
  | 'DAMAGE_REPORTED'
  | 'ACCOUNT_APPROVED'
  | 'ACCOUNT_REJECTED'
  | 'ACCOUNT_SUSPENDED'
  | 'ACCOUNT_UNSUSPENDED'
  | 'TRIAL_EXPIRING_SOON'
  | 'SUBSCRIPTION_EXPIRING_SOON'
  | 'GRACE_PERIOD_STARTED'
  | 'SUBSCRIPTION_EXPIRED'
  | 'SUBSCRIPTION_ACTIVATED'
  | 'PAYMENT_REQUEST_CONFIRMED'
  | 'PAYMENT_REQUEST_REJECTED'
  | 'SESSION_CHECKOUT_INSPECTION'
  | 'SESSION_EXTENSION_PROPOSED'
  | 'SESSION_FNB_ORDER_ADDED'
  | 'FNB_ORDER_READY_FOR_PREP'
  | 'FNB_ORDER_SERVED'
  | 'CUSTOMER_CHECKIN_CONFIRMED'
  | 'CUSTOMER_CHECKOUT_CONFIRMED'
  | 'CUSTOMER_INSPECTION_DISPUTED'
  | 'CUSTOMER_EXTENSION_APPROVED'
  | 'CUSTOMER_EXTENSION_REJECTED'
  | 'CUSTOMER_PAYMENT_CONFIRMED'
  | 'BOOKING_REVIEW_REQUEST'
  | 'CONTEST_REGISTRATION_CREATED'
  | 'CONTEST_REGISTRATION_APPROVED'
  | 'CONTEST_REGISTRATION_REJECTED'
  | 'CONTEST_REGISTRATION_CANCELLED'
  | 'CONTEST_CHECKIN_CONFIRMED'
  | 'CONTEST_REMINDER'
  | (string & {})

export interface Notification {
  id: string
  userId: string
  type: NotificationType
  title: string
  message: string
  data: Record<string, unknown> | null
  readAt: string | null
  createdAt: string
}

export interface NotificationListResponse {
  data: Notification[]
  total: number
  unreadCount: number
}
