import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  specsSidebar: [
    {
      type: 'category',
      label: '001 · User Login',
      collapsed: true,
      items: [
        'user-login/spec',
        'user-login/plan',
        'user-login/data-model',
        'user-login/research',
        'user-login/quickstart',
        'user-login/tasks',
        'user-login/contracts/auth',
      ],
    },
    {
      type: 'category',
      label: '002 · Branch AI Chat RAG',
      collapsed: true,
      items: [
        'branch-ai-chat-rag/spec',
        'branch-ai-chat-rag/plan',
        'branch-ai-chat-rag/data-model',
        'branch-ai-chat-rag/research',
        'branch-ai-chat-rag/quickstart',
        'branch-ai-chat-rag/tasks',
        'branch-ai-chat-rag/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '003 · FB Messenger Channel',
      collapsed: true,
      items: [
        'fb-messenger-channel/spec',
        'fb-messenger-channel/plan',
        'fb-messenger-channel/data-model',
        'fb-messenger-channel/research',
        'fb-messenger-channel/quickstart',
        'fb-messenger-channel/tasks',
        'fb-messenger-channel/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '004 · Provider Subscription',
      collapsed: true,
      items: [
        'provider-subscription/spec',
        'provider-subscription/plan',
        'provider-subscription/data-model',
        'provider-subscription/research',
        'provider-subscription/quickstart',
        'provider-subscription/tasks',
        'provider-subscription/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '005 · Provider Detail & Impersonation',
      collapsed: true,
      items: [
        'provider-detail-impersonation/spec',
        'provider-detail-impersonation/plan',
        'provider-detail-impersonation/data-model',
        'provider-detail-impersonation/research',
        'provider-detail-impersonation/quickstart',
        'provider-detail-impersonation/tasks',
        'provider-detail-impersonation/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '006 · Staff Invite Management',
      collapsed: true,
      items: [
        'staff-invite-management/spec',
        'staff-invite-management/plan',
        'staff-invite-management/data-model',
        'staff-invite-management/research',
        'staff-invite-management/quickstart',
        'staff-invite-management/tasks',
        'staff-invite-management/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '007 · Booking Payment',
      collapsed: true,
      items: [
        'booking-payment/spec',
        'booking-payment/plan',
        'booking-payment/data-model',
        'booking-payment/research',
        'booking-payment/quickstart',
        'booking-payment/tasks',
        'booking-payment/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '008 · Cafe Track Config',
      collapsed: true,
      items: [
        'cafe-track-config/spec',
        'cafe-track-config/plan',
        'cafe-track-config/data-model',
        'cafe-track-config/research',
        'cafe-track-config/quickstart',
        'cafe-track-config/tasks',
        'cafe-track-config/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '009 · Customer Package Booking',
      collapsed: true,
      items: [
        'customer-package-booking/spec',
        'customer-package-booking/plan',
        'customer-package-booking/data-model',
        'customer-package-booking/research',
        'customer-package-booking/quickstart',
        'customer-package-booking/tasks',
        'customer-package-booking/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '010 · AI Revenue Analytics',
      collapsed: true,
      items: [
        'ai-revenue-analytics/spec',
        'ai-revenue-analytics/plan',
        'ai-revenue-analytics/tasks',
      ],
    },
    {
      type: 'category',
      label: '011 · Booking Review & Rating',
      collapsed: true,
      items: [
        'booking-review/spec',
        'booking-review/plan',
        'booking-review/research',
        'booking-review/data-model',
        'booking-review/quickstart',
        'booking-review/contracts/api',
        'booking-review/tasks',
      ],
    },
    {
      type: 'category',
      label: '012 · Provider KYC Verification',
      collapsed: true,
      items: [
        'provider-kyc/spec',
        'provider-kyc/plan',
        'provider-kyc/data-model',
        'provider-kyc/research',
        'provider-kyc/quickstart',
        'provider-kyc/tasks',
        'provider-kyc/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '014 · Staff KPI Dashboard',
      collapsed: true,
      items: [
        'staff-kpi-dashboard/spec',
        'staff-kpi-dashboard/plan',
        'staff-kpi-dashboard/data-model',
        'staff-kpi-dashboard/research',
        'staff-kpi-dashboard/quickstart',
        'staff-kpi-dashboard/tasks',
        'staff-kpi-dashboard/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '016 · Damage Charge Redesign',
      collapsed: true,
      items: [
        'damage-charge-redesign/spec',
        'damage-charge-redesign/plan',
        'damage-charge-redesign/data-model',
        'damage-charge-redesign/research',
        'damage-charge-redesign/quickstart',
        'damage-charge-redesign/tasks',
        'damage-charge-redesign/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '017 · Custom Menu Categories',
      collapsed: true,
      items: [
        'custom-menu-categories/spec',
        'custom-menu-categories/plan',
        'custom-menu-categories/data-model',
        'custom-menu-categories/research',
        'custom-menu-categories/quickstart',
        'custom-menu-categories/tasks',
        'custom-menu-categories/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '018 · Contest Finance',
      collapsed: true,
      items: [
        'contest-finance/spec',
        'contest-finance/plan',
        'contest-finance/research',
        'contest-finance/data-model',
        'contest-finance/quickstart',
        'contest-finance/contracts/api',
      ],
    },
    {
      type: 'category',
      label: '019 · Thanh toán chuyển khoản theo chi nhánh',
      collapsed: true,
      items: [
        'cafe-bank-payment/spec',
        'cafe-bank-payment/plan',
        'cafe-bank-payment/research',
        'cafe-bank-payment/data-model',
        'cafe-bank-payment/quickstart',
        'cafe-bank-payment/tasks',
        'cafe-bank-payment/contracts/api',
      ],
    },
  ],
};

export default sidebars;
